
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 26 22:15:37 CEST 2014
//----------------------------------------------------

package compilplic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int MOD = 6;
  public static final int IDF = 12;
  public static final int LT = 8;
  public static final int S_NOUVEAU = 22;
  public static final int S_DEBUT = 20;
  public static final int S_CLASSE = 16;
  public static final int PLUS = 2;
  public static final int EQUAL = 27;
  public static final int STATUT = 19;
  public static final int S_RETOURNE = 21;
  public static final int POINT = 28;
  public static final int S_FIN = 15;
  public static final int VIRGULE = 23;
  public static final int GT = 7;
  public static final int MOINS = 3;
  public static final int CSTE_ENT = 13;
  public static final int S_ECRIRE = 18;
  public static final int PARENTH_OUVRANTE = 24;
  public static final int CSTE_CHAINE = 14;
  public static final int DOUBLE_EQUAL = 9;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int S_LIRE = 17;
  public static final int POINT_VIRGULE = 26;
  public static final int DIFF = 10;
  public static final int PARENTH_FERMANTE = 25;
  public static final int TYPE_PRIMITIF = 11;
}

